// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaNOlu0NsUpGxgFAw8RV2UCKvvBAXqXrY',
    appId: '1:536853038356:web:e58e8ca8865d6e0a9fae01',
    messagingSenderId: '536853038356',
    projectId: 'frases-do-dia-78460',
    authDomain: 'frases-do-dia-78460.firebaseapp.com',
    storageBucket: 'frases-do-dia-78460.firebasestorage.app',
    measurementId: 'G-06H2EB4DG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2Aww0cLGlG8QY_Lparsuw224uPfAySs',
    appId: '1:536853038356:android:555eca85d9666aa19fae01',
    messagingSenderId: '536853038356',
    projectId: 'frases-do-dia-78460',
    storageBucket: 'frases-do-dia-78460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbFjZvDtOOmCWB0tj7XjrStft0zurbRTQ',
    appId: '1:536853038356:ios:874c716f511870a29fae01',
    messagingSenderId: '536853038356',
    projectId: 'frases-do-dia-78460',
    storageBucket: 'frases-do-dia-78460.firebasestorage.app',
    iosBundleId: 'com.example.appFrasesdodia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbFjZvDtOOmCWB0tj7XjrStft0zurbRTQ',
    appId: '1:536853038356:ios:874c716f511870a29fae01',
    messagingSenderId: '536853038356',
    projectId: 'frases-do-dia-78460',
    storageBucket: 'frases-do-dia-78460.firebasestorage.app',
    iosBundleId: 'com.example.appFrasesdodia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaNOlu0NsUpGxgFAw8RV2UCKvvBAXqXrY',
    appId: '1:536853038356:web:4435ac8b2ac18dc89fae01',
    messagingSenderId: '536853038356',
    projectId: 'frases-do-dia-78460',
    authDomain: 'frases-do-dia-78460.firebaseapp.com',
    storageBucket: 'frases-do-dia-78460.firebasestorage.app',
    measurementId: 'G-4ELCC7R65R',
  );
}
